stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build-docs:
  stage: build
  image: python
  before_script:
    - pip install tox
  script:
    - tox -e docs
  artifacts:
    paths: 
      - docs
build-job:       # This job runs in the build stage, which runs first.
  stage: deploy
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/docker/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
pages:
  stage: deploy
  image: python
  script:
   - mv docs/_build/html public
  artifacts:
    paths:
      - public

